name: check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest deno version
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Run deno fmt
        run: deno fmt --check

      - name: Run deno lint
        run: deno lint --unstable

  test:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest deno version
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Run deno test
        run: deno test --allow-all --unstable
